# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_offeryear_subject_to_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('number_session', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicCalendar')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sessionexamcalendar',
            unique_together=set([('number_session', 'academic_calendar')]),
        ),
    ]
